<!--#if (UseWebSdk) -->
<Project Sdk="Microsoft.NET.Sdk.Web">
<!--#else -->
<Project Sdk="Microsoft.NET.Sdk">
<!--#endif -->

  <!-- General build settings: defines the output type and target framework -->
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>__TargetFrameworks__</TargetFrameworks>
    <TargetFramework>__TargetFramework__</TargetFramework>
  </PropertyGroup>

  <!-- Packaging and publish configuration -->
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <IsPublishable>true</IsPublishable>
    <IsTestProject>false</IsTestProject>
    <PackAsTool>false</PackAsTool>
  </PropertyGroup>

  <!-- C# language features and debugging configuration -->
  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!-- Versioning -->
  <PropertyGroup>
    <VersionMajor>0</VersionMajor>
    <VersionMinor>1</VersionMinor>
    <VersionBuild>0</VersionBuild>
    <VersionRevision>0</VersionRevision>
    <VersionPrefix>$(VersionMajor).$(VersionMinor).$(VersionBuild).$(VersionRevision)</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' == '' and '$(Configuration)' == 'Debug'">prerelease</VersionSuffix>
    <PackageVersion Condition="'$(VersionSuffix)' == ''">$(VersionPrefix)</PackageVersion>
    <PackageVersion Condition="'$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</PackageVersion>
    <InformationalVersion>$(PackageVersion)</InformationalVersion>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
  </PropertyGroup>

  <!-- Package metadata -->
  <!-- https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices -->
  <PropertyGroup>
    <Authors>MyAuthor</Authors>
    <!--#if (PackageCopyrightHolderIsSet) -->
    <Owners>MyCopyrightHolder</Owners>
    <!--#else -->
    <Owners>MyAuthor</Owners>
    <!--#endif -->
    <!--#if (PackageCopyrightHolderIsOrganization == true) -->
    <!--#if (PackageCopyrightHolderIsSet) -->
    <Company>MyCopyrightHolder</Company>
    <!--#else -->
    <Company>MyAuthor</Company>
    <!--#endif -->
    <!--#else -->
    <Company></Company>
    <!--#endif -->
    <!--#if (PackageCopyrightHolderIsSet) -->
    <Copyright>Copyright © 1975 MyCopyrightHolder</Copyright>
    <!--#else -->
    <Copyright>Copyright © 1975 MyAuthor</Copyright>
    <!--#endif -->
    <PackageId>ClassLibrary</PackageId>
    <PackageTags>dotnet;class;library</PackageTags>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl></RepositoryUrl>
    <RepositoryType></RepositoryType>
    <Description>
     <![CDATA[PackageDescription]]>
    </Description>
    <PackageReadmeFile>Readme.md</PackageReadmeFile>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
    <PackageIcon>Icon-128x128.png</PackageIcon>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)\NugetAssets\ReleaseNotes.txt"))</PackageReleaseNotes>
  </PropertyGroup>

  <!-- Package specs -->
  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)\NugetAssets\**\*" Pack="true" PackagePath="" />
  </ItemGroup>

  <PropertyGroup>
    <PackageOutputPath Condition=" '$(PackageOutputPath)' == '' ">$(MSBuildProjectDirectory)\bin\Pack</PackageOutputPath>
    <LocalPackagesDir></LocalPackagesDir>
  </PropertyGroup>

  <!-- Publish behavior keep slim for library specs -->
	<PropertyGroup Condition="'$(_IsPublishing)' == 'true'">
		<!-- Flat publish output -->
		<PublishDir Condition="'$(PublishDir)' == ''">$(MSBuildProjectDirectory)\bin\Publish\</PublishDir>
		<PublishAot>false</PublishAot>
		<PublishTrimmed>false</PublishTrimmed>
	</PropertyGroup>

  <!-- Publish behavior for executable future useage program main etc -->
	<PropertyGroup Condition="'$(_IsPublishing)' == 'true' and '$(OutputType)' != 'Library'">
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSelfContained>true</PublishSelfContained>
		<PublishSingleFile>true</PublishSingleFile>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>

  <Target Name="CopyToLocalPackages" AfterTargets="Pack" Condition="'$(LocalPackagesDir)'!=''">
    <Message Text="Copy $(PackageOutputPath)/$(PackageId).$(PackageVersion).nupkg to $(LocalPackagesDir)" Importance="high" />
    <Copy SourceFiles="$(PackageOutputPath)/$(PackageId).$(PackageVersion).nupkg" DestinationFolder="$(LocalPackagesDir)"  />
  </Target>

  <!-- Import for pack target multiplaform build for pack always -->
  <Import Project="Build/BuildForPack.targets" />
  <!-- Import for version information already integrated in < net8.0 -->
  <Import Project="Build/SourceControlState.targets" />

</Project>
