#!/usr/bin/env bash
GOTO :WIN
if [ $(uname) == 'Linux'  ]
then
	clear
	curl -sSL https://raw.githubusercontent.com/carsten-riedel/Coree.Template.Project/main/raw/init.sh | bash
	exit
fi

:WIN
@echo off
if "%comspec%" == "C:\Windows\system32\cmd.exe" (
 cls
	curl -sSL https://raw.githubusercontent.com/carsten-riedel/Coree.Template.Project/main/raw/init.bat | cmd
)