using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace __SourceName__
{
    /// <summary>
    /// Generates a small <c>TypeNameJson</c> helper for classes marked with
    /// <c>GenerateJsonSupportAttribute</c> in the consuming project.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class JsonSupportGenerator : IIncrementalGenerator
    {
        internal const string DiagnosticId = "JSG001";
        internal const string AttributeMetadataName = "__SourceName__.GenerateJsonSupportAttribute";

        private const string AttributeSource = """
            // <auto-generated />
            #nullable enable

            namespace __SourceName__
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                internal sealed class GenerateJsonSupportAttribute : global::System.Attribute
                {
                }
            }
            """;

        private static readonly DiagnosticDescriptor UnsupportedTarget = new(
            DiagnosticId,
            "JSON support target is not supported",
            "Type '{0}' must be a top-level, non-generic, non-static class with public or internal accessibility",
            "SourceGeneration",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true);

        /// <summary>
        /// Registers the marker attribute and the incremental generation pipeline.
        /// </summary>
        /// <param name="context">The generator initialization context.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static output =>
                output.AddSource("GenerateJsonSupportAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

            var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is TypeDeclarationSyntax,
                static (syntaxContext, _) => CreateTarget(syntaxContext));

            context.RegisterSourceOutput(targets, static (sourceContext, target) => Emit(sourceContext, target));
        }

        private static JsonTarget CreateTarget(GeneratorAttributeSyntaxContext context)
        {
            var type = (INamedTypeSymbol)context.TargetSymbol;
            var declaration = (TypeDeclarationSyntax)context.TargetNode;
            var displayName = type.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);

            if (type.ContainingType is not null ||
                type.Arity != 0 ||
                type.IsStatic ||
                type.IsFileLocal)
            {
                return JsonTarget.Unsupported(displayName, declaration.Identifier.GetLocation());
            }

            var namespaceName = type.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : type.ContainingNamespace.ToDisplayString();
            var accessibility = type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
            var fullyQualifiedName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            return JsonTarget.Supported(
                namespaceName,
                type.Name,
                fullyQualifiedName,
                accessibility,
                declaration.Identifier.GetLocation());
        }

        private static void Emit(SourceProductionContext context, JsonTarget target)
        {
            if (target.ErrorTypeName is not null)
            {
                context.ReportDiagnostic(Diagnostic.Create(UnsupportedTarget, target.Location, target.ErrorTypeName));
                return;
            }

            var namespaceOpen = target.NamespaceName.Length == 0
                ? string.Empty
                : "namespace " + target.NamespaceName + "\n{\n";
            var namespaceClose = target.NamespaceName.Length == 0 ? string.Empty : "}\n";
            var indent = target.NamespaceName.Length == 0 ? string.Empty : "    ";
            var helperName = target.TypeName + "Json";

            var source = $$"""
                // <auto-generated />
                #nullable enable

                {{namespaceOpen}}{{indent}}/// <summary>JSON serialization helpers generated for <see cref="{{target.FullyQualifiedName}}"/>.</summary>
                {{indent}}{{target.Accessibility}} static class {{helperName}}
                {{indent}}{
                {{indent}}    /// <summary>Serializes <paramref name="value"/> as JSON.</summary>
                {{indent}}    public static string Serialize({{target.FullyQualifiedName}} value, bool writeIndented = true)
                {{indent}}    {
                {{indent}}        if (value is null)
                {{indent}}        {
                {{indent}}            throw new global::System.ArgumentNullException(nameof(value));
                {{indent}}        }

                {{indent}}        return global::System.Text.Json.JsonSerializer.Serialize(
                {{indent}}            value,
                {{indent}}            new global::System.Text.Json.JsonSerializerOptions { WriteIndented = writeIndented });
                {{indent}}    }

                {{indent}}    /// <summary>Deserializes JSON into <see cref="{{target.FullyQualifiedName}}"/>.</summary>
                {{indent}}    public static {{target.FullyQualifiedName}}? Deserialize(string json)
                {{indent}}    {
                {{indent}}        if (json is null)
                {{indent}}        {
                {{indent}}            throw new global::System.ArgumentNullException(nameof(json));
                {{indent}}        }

                {{indent}}        return global::System.Text.Json.JsonSerializer.Deserialize<{{target.FullyQualifiedName}}>(json);
                {{indent}}    }
                {{indent}}}
                {{namespaceClose}}
                """;

            var hintName = (target.NamespaceName.Length == 0
                ? target.TypeName
                : target.NamespaceName + "." + target.TypeName) + ".JsonSupport.g.cs";

            context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
        }

        private sealed class JsonTarget
        {
            private JsonTarget(
                string namespaceName,
                string typeName,
                string fullyQualifiedName,
                string accessibility,
                string? errorTypeName,
                Location location)
            {
                NamespaceName = namespaceName;
                TypeName = typeName;
                FullyQualifiedName = fullyQualifiedName;
                Accessibility = accessibility;
                ErrorTypeName = errorTypeName;
                Location = location;
            }

            internal string NamespaceName { get; }

            internal string TypeName { get; }

            internal string FullyQualifiedName { get; }

            internal string Accessibility { get; }

            internal string? ErrorTypeName { get; }

            internal Location Location { get; }

            internal static JsonTarget Supported(
                string namespaceName,
                string typeName,
                string fullyQualifiedName,
                string accessibility,
                Location location)
            {
                return new JsonTarget(
                    namespaceName,
                    typeName,
                    fullyQualifiedName,
                    accessibility,
                    errorTypeName: null,
                    location);
            }

            internal static JsonTarget Unsupported(string displayName, Location location)
            {
                return new JsonTarget(
                    namespaceName: string.Empty,
                    typeName: string.Empty,
                    fullyQualifiedName: string.Empty,
                    accessibility: string.Empty,
                    displayName,
                    location);
            }
        }
    }
}
